export const data = [
    {
        id: "1",
        src: ["/pizza1.png", "/pizza2.png"],
        title: "Margherita",
        description: "Tomato, Mozzarella, Bell Peppers, Onions, Olives",
        price: 150,
        restaurantLogo: "/image1.png",
        restaurantName: "Azmera Pizza",
        category: "Fasting",
        recipes: ["Mozzarella", "Tomato", " Bell Peppers", "Onions", "Olives"],
        status: "",
    },
    {
        id: "2",
        src: ["/pizza1.png", "/pizza2.png"],
        title: "Margherita",
        description: "Tomato, Mozzarella, Bell Peppers, Onions, Olives",
        price: 150,
        restaurantLogo: "/image1.png",
        restaurantName: "Azmera Pizza",
        category: "Fasting",
        recipes: ["Mozzarella", "Tomato", " Bell Peppers", "Onions", "Olives"],
        status: "",
    },
    {
        id: "3",
        src: ["/pizza1.png", "/pizza2.png"],
        title: "Margherita",
        description: "Tomato, Mozzarella, Bell Peppers, Onions, Olives",
        price: 150,
        restaurantLogo: "/image1.png",
        restaurantName: "Azmera Pizza",
        category: "Fasting",
        recipes: ["Mozzarella", "Tomato", " Bell Peppers", "Onions", "Olives"],
        status: "",
    },
    {
        id: "4",
        src: ["/pizza1.png", "/pizza2.png"],
        title: "Margherita",
        description: "Tomato, Mozzarella, Bell Peppers, Onions, Olives",
        price: 150,
        restaurantLogo: "/image1.png",
        restaurantName: "Azmera Pizza",
        category: "Normal",
        recipes: ["Mozzarella", "Tomato", " Bell Peppers", "Onions", "Olives"],
        status: "",
    },
    {
        id: "5",
        src: ["/pizza1.png", "/pizza2.png"],
        title: "Margherita",
        description: "Tomato, Mozzarella, Bell Peppers, Onions, Olives",
        price: 150,
        restaurantLogo: "/image1.png",
        restaurantName: "Azmera Pizza",
        category: "Normal",
        recipes: ["Mozzarella", "Tomato", " Bell Peppers", "Onions", "Olives"],
        status: "",
    },
    {
        id: "6",
        src: ["/pizza1.png", "/pizza2.png"],
        title: "Margherita",
        description: "Tomato, Mozzarella, Bell Peppers, Onions, Olives",
        price: 150,
        restaurantLogo: "/image1.png",
        restaurantName: "Azmera Pizza",
        category: "Normal",
        recipes: ["Mozzarella", "Tomato", " Bell Peppers", "Onions", "Olives"],
        status: "",
    },
];

export const orderedData = [
    {
        id: "1",
        src: ["/pizza1.png", "/pizza2.png"],
        title: "Margherita",
        description: "Tomato, Mozzarella, Bell Peppers, Onions, Olives",
        price: 150,
        restaurantLogo: "/image1.png",
        restaurantName: "Azmera Pizza",
        status: "Pending",
        recipes: ["Mozzarella", "Tomato", " Bell Peppers", "Onions", "Olives"],
        category: "Fasting",
    },
    {
        id: "2",
        src: ["/pizza1.png", "/pizza2.png"],
        title: "Margherita",
        description: "Tomato, Mozzarella, Bell Peppers, Onions, Olives",
        price: 150,
        restaurantLogo: "/image1.png",
        restaurantName: "Azmera Pizza",
        status: "Pending",
        recipes: ["Mozzarella", "Tomato", " Bell Peppers", "Onions", "Olives"],
        category: "Fasting",
    },
    {
        id: "3",
        src: ["/pizza1.png", "/pizza2.png"],
        title: "Margherita",
        description: "Tomato, Mozzarella, Bell Peppers, Onions, Olives",
        price: 150,
        restaurantLogo: "/image1.png",
        restaurantName: "Azmera Pizza",
        status: "Delivered",
        recipes: ["Mozzarella", "Tomato", " Bell Peppers", "Onions", "Olives"],
        category: "Fasting",
    },
    {
        id: "4",
        src: ["/pizza1.png", "/pizza2.png"],
        title: "Margherita",
        description: "Tomato, Mozzarella, Bell Peppers, Onions, Olives",
        price: 150,
        restaurantLogo: "/image1.png",
        restaurantName: "Azmera Pizza",
        status: "Delivered",
        recipes: ["Mozzarella", "Tomato", " Bell Peppers", "Onions", "Olives"],
        category: "Fasting",
    },
    {
        id: "5",
        src: ["/pizza1.png", "/pizza2.png"],
        title: "Margherita",
        description: "Tomato, Mozzarella, Bell Peppers, Onions, Olives",
        price: 150,
        restaurantLogo: "/image1.png",
        restaurantName: "Azmera Pizza",
        status: "Delivered",
        recipes: ["Mozzarella", "Tomato", " Bell Peppers", "Onions", "Olives"],
        category: "Normal",
    },
    {
        id: "6",
        src: ["/pizza1.png", "/pizza2.png"],
        title: "Margherita",
        description: "Tomato, Mozzarella, Bell Peppers, Onions, Olives",
        price: 150,
        restaurantLogo: "/image1.png",
        restaurantName: "Azmera Pizza",
        status: "Delivered",
        recipes: ["Mozzarella", "Tomato", " Bell Peppers", "Onions", "Olives"],
        category: "Normal",
    },
];